apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-house-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-house-app
  template:
    metadata:
      labels:
        app: flask-house-app
    spec:
      containers:
      - name: flask-house-app
        image: pramodhm/flask-house-app:v1
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
        ports:
        - containerPort: 5000
